// Local CSS-like types so @flemo/core stays independent of any animation
// library. Mirrors the subset of motion's Target / AnimationOptions that
// flemo actually compiles. The keyframes compiler accepts these shapes for
// `transition.initial`, variant `value`, and the imperative inline animator.

export type AnimationEasing =
  | string
  | readonly [number, number, number, number]
  | [number, number, number, number];

export interface AnimationOptions {
  duration?: number;
  ease?: AnimationEasing;
  delay?: number;
}

// Properties the compiler turns into CSS. Numeric values without an explicit
// unit are interpreted as px (x/y/z), degrees (rotate*), or raw scalars
// (scale*, opacity). String values pass through verbatim, so callers can use
// "100%", "1rem", "rgba(...)", etc.
export interface TransitionTarget {
  x?: string | number;
  y?: string | number;
  z?: string | number;
  scale?: string | number;
  scaleX?: string | number;
  scaleY?: string | number;
  rotate?: string | number;
  rotateX?: string | number;
  rotateY?: string | number;
  rotateZ?: string | number;
  opacity?: number | string;
  backgroundColor?: string;
  // Anything else falls through to CSS — kebab-case is generated by the
  // compiler, so authors can write camelCase as in inline React styles.
  [key: string]: string | number | undefined;
}

// `initial` historically allowed transition options too (Motion's
// TargetAndTransition). The compiler only inspects the target half — option
// fields on `initial` are ignored.
export type InitialTarget = TransitionTarget;
